// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FavoriteController from "./favorite_controller"
application.register("favorite", FavoriteController)

import FavoriteToggleController from "./favorite_toggle_controller"
application.register("favorite-toggle", FavoriteToggleController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import IngredientValueController from "./ingredient_value_controller"
application.register("ingredient-value", IngredientValueController)

import MapController from "./map_controller"
application.register("map", MapController)

import ModalTransitionController from "./modal_transition_controller"
application.register("modal-transition", ModalTransitionController)

import ReviewsController from "./reviews_controller"
application.register("reviews", ReviewsController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)
